// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcqmlylbhdgouyfzfdtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjcW1seWxiaGRnb3V5ZnpmZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDAzNjUsImV4cCI6MjA2NTU3NjM2NX0.N6_rzf9k21lrdhtrbl8b3xf59AY4ztEDwxAH3a45z6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);